// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEBDOM_SAS.Data;

#nullable disable

namespace SEBDOM_SAS.Migrations
{
    [DbContext(typeof(SEBDOM_SASContext))]
    [Migration("20250514014432_pulpo")]
    partial class pulpo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SEBDOM_SAS.Models.GavetaPulpo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPulpos")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroGaveta")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoLbs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RegistroPulpoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroPulpoId");

                    b.ToTable("GavetasPulpo");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.Historial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockNuevo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Historial");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.ProveedorPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PrecioEspecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioNormal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RegistroPulpoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroPulpoId");

                    b.ToTable("ProveedoresPrecios");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.RegistroPulpo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigosSeleccionados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegistrosPulpo");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.GavetaPulpo", b =>
                {
                    b.HasOne("SEBDOM_SAS.Models.RegistroPulpo", "RegistroPulpo")
                        .WithMany("Gavetas")
                        .HasForeignKey("RegistroPulpoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPulpo");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.Historial", b =>
                {
                    b.HasOne("SEBDOM_SAS.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.ProveedorPrecio", b =>
                {
                    b.HasOne("SEBDOM_SAS.Models.RegistroPulpo", "RegistroPulpo")
                        .WithMany("ProveedoresPrecios")
                        .HasForeignKey("RegistroPulpoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPulpo");
                });

            modelBuilder.Entity("SEBDOM_SAS.Models.RegistroPulpo", b =>
                {
                    b.Navigation("Gavetas");

                    b.Navigation("ProveedoresPrecios");
                });
#pragma warning restore 612, 618
        }
    }
}
